name: info5368
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - anyio=4.1.0
  - aom=3.5.0
  - appnope=0.1.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - atk-1.0=2.38.0
  - attrs=20.3.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - box2d-py=2.3.8
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.26.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.12
  - click=7.1.2
  - colorama=0.4.6
  - comm=0.2.1
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - expat=2.5.0
  - ffmpeg=4.4.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - ftfy=6.0.3
  - future=0.18.3
  - gdk-pixbuf=2.42.8
  - gettext=0.21.1
  - giflib=5.2.1
  - gitdb=4.0.11
  - gitpython=3.1.41
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - graphviz=5.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=4.4.1
  - hdf5=1.12.1
  - icu=70.1
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_resources=6.1.1
  - ipykernel=6.29.0
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.6
  - isoduration=20.11.0
  - jasper=2.0.33
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=0.14.1
  - jpeg=9e
  - jsonpointer=2.4
  - jsonschema=4.17.3
  - jsonschema-with-format-nongpl=4.17.3
  - jupyter=1.0.0
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.7.1
  - jupyter_events=0.6.3
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.5.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_widgets=1.1.7
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libiconv=1.17
  - libidn2=2.3.7
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.58.0
  - libopenblas=0.3.25
  - libopencv=4.5.5
  - libpng=1.6.42
  - libprotobuf=3.20.3
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libtiff=4.3.0
  - libtool=2.4.7
  - libunistring=0.9.10
  - libvpx=1.11.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - markupsafe=2.1.5
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.14.2
  - nbconvert-core=7.14.2
  - nbconvert-pandoc=7.14.2
  - nbdime=3.1.1
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - nltk=3.6.7
  - notebook=6.5.6
  - notebook-shim=0.2.3
  - numexpr=2.7.3
  - numpy=1.19.5
  - olefile=0.47
  - opencv=4.5.5
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.2.1
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=20.9
  - pandas=1.3.5
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - pango=1.50.8
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=23.3.2
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - py-opencv=4.5.5
  - pycparser=2.21
  - pyglet=1.5.27
  - pygments=2.17.2
  - pyobjc-core=10.1
  - pyobjc-framework-cocoa=10.1
  - pyopengl=3.1.6
  - pyparsing=3.1.1
  - pyrsistent=0.20.0
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-graphviz=0.20.1
  - python-json-logger=2.0.7
  - python_abi=3.8
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=24.0.1
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - readline=8.2
  - regex=2023.12.25
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - seaborn
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - send2trash=1.8.2
  - setuptools=59.8.0
  - six=1.15.0
  - smmap=5.0.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - svt-av1=1.4.1
  - terminado=0.18.0
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tornado=6.3.3
  - tqdm=4.62.3
  - traitlets=5.14.1
  - types-python-dateutil=2.8.19.20240106
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - urllib3=1.26.18
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.42.0
  - widgetsnbextension=3.5.2
  - x264=1!164.3095
  - x265=3.5
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - altair==5.2.0
      - backports-zoneinfo==0.2.1
      - blinker==1.7.0
      - cachetools==5.3.2
      - iniconfig==2.0.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - plotly==5.18.0
      - pluggy==1.4.0
      - protobuf==4.25.2
      - pyarrow==15.0.0
      - pydeck==0.8.1b0
      - pytest==8.0.0
      - pytest-mock==3.12.0
      - requests==2.31.0
      - rich==13.7.0
      - streamlit==1.31.0
      - tenacity==8.2.3
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.1
      - typing-extensions==4.9.0
      - tzlocal==5.2
      - validators==0.22.0